JAVA_MIN_HEAP=1024m
JAVA_MAX_HEAP=1024m

JAVA_STACK_SIZE=512k
#JAVA_PERMENENT_GENERATION_SIZE=128m
JAVA_YOUNG_GENERATION_SIZE=128m

CATALINA_OPTS="${CATALINA_OPTS} -Xms${JAVA_MIN_HEAP} -Xmx${JAVA_MAX_HEAP} -Xss${JAVA_STACK_SIZE} -Xmn${JAVA_YOUNG_GENERATION_SIZE} -server
